name: Pull Request Test

on: 
  pull_request:
    branches: 
      - main

jobs:
  build_manylinux:
    name: Build for manylinux2010
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2010_x86_64
    strategy:
      max-parallel: 4
      matrix:
        cp: [cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install numpy==`/opt/python/${{ matrix.cp }}/bin/python .github/workflows/numpy_version.py`
        /opt/python/${{ matrix.cp }}/bin/python setup.py build install

    - run: tar -zcvf build.tgz build
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: Linux Binary ${{ matrix.cp }}
        path: build.tgz

  build_manylinux2014:
    name: Build for manylinux2014
    runs-on: ubuntu-latest
    container:
      image: docker://quay.io/pypa/manylinux2014_x86_64
    strategy:
      max-parallel: 4
      matrix:
        cp: [cp311-cp311]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: |
        /opt/python/${{ matrix.cp }}/bin/python -m pip install numpy==`/opt/python/${{ matrix.cp }}/bin/python .github/workflows/numpy_version.py`
        /opt/python/${{ matrix.cp }}/bin/python setup.py build install

    - run: tar -zcvf build.tgz build
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: Linux Binary ${{ matrix.cp }}
        path: build.tgz

  build_macos_11:
    name: Build for macOS 11
    runs-on: macOS-11
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        python -m pip install numpy==`python .github/workflows/numpy_version.py`
        MACOSX_DEPLOYMENT_TARGET=10.14 CG_CPU_ARCH=arm64 python setup.py build
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: macOS Binary ${{ matrix.python-version }} ${{ matrix.architecture }}
        path: |
          build/*

  build_windows:
    name: Build for Windows
    runs-on: windows-2019
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]
        architecture: [x86, x64]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Build
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install numpy==$(python .github/workflows/numpy_version.py)
        python setup.py build install
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: Windows Binary ${{ matrix.python-version }} ${{ matrix.architecture }}
        path: |
          build/*
